services:
  - type: web
    name: blud-client
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node discord-key-bot/index.js
    envVars:
      - key: NODE_ENV
        value: production
